name: Makefile CI

on:
  push:
    branches: [ "vext_x6833b_h894-user-12-SP1A.210812.016-367846-release-keys" ]
  pull_request:
    branches: [ "vext_x6833b_h894-user-12-SP1A.210812.016-367846-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python
    
    - name: build
      run: sudo chmod 777 setup-makefiles.sh && ./setup-makefiles.sh

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *
